/**
 * nonVisualDatabase.js
 * Non-visible genetic traits — syndromes, physiological variants, abilities, conditions.
 */

const NON_VISUAL_DB = {

  neurological: {
    label: 'Neurological & Sensory',
    icon: '🧠',
    traits: [
      {
        id: 'faah_out',
        name: 'FAAH-OUT Mutation (Pain Insensitivity)',
        icon: '🛡',
        gene: 'FAAH-OUT pseudogene + FAAH',
        snp: 'rs324420 (FAAH C385A) + ~8kb microdeletion chr1',
        chr: '1p33',
        allele: 'FAAH(C385A/A385A) + FAAH-OUT del/wt',
        mechanism: 'FAAH-OUT microdeletion silences FAAH pseudogene regulatory region. Combined with FAAH hypomorphic SNP, FAAH enzyme activity collapses → anandamide levels 70% higher than normal → near-complete pain insensitivity, reduced anxiety, accelerated wound healing, enhanced fear-extinction memory.',
        effects: ['Near-complete pain insensitivity', 'Reduced anxiety (GAD score 0/21)', 'Rapid wound healing', 'Enhanced fear extinction', 'Short-term memory lapses', 'No panic response'],
        code: 'FAAH(rs324420 C→A/A, C385A) + FAAH-OUT(~8kb microdeletion chr1p33) | OMIM #618377',
        frequency: 'Extremely rare — only handful of documented cases worldwide',
        heritage: 'Autosomal; first case: Jo Cameron, Scottish woman, 1950s–present',
        source: 'Habib et al. (2019), Br J Anaesth — DOI: 10.1016/j.bja.2019.02.019',
        badges: ['advantage', 'rare'],
      },
      {
        id: 'tetrachromacy',
        name: 'Tetrachromacy (4-Color Vision)',
        icon: '🌈',
        gene: 'OPN1MW / OPN1MW2',
        snp: 'OPN1MW2 duplication + specific spectral tuning variants',
        chr: 'Xq28',
        allele: 'Extra M-cone opsin allele (X-linked)',
        mechanism: 'Some women carry two different OPN1MW alleles on each X chromosome producing four distinct cone types (vs normal 3). This allows discrimination of ~100 million colors vs ~1 million in trichromats.',
        effects: ['~100 million discernible colors', 'Female-limited expression (X-linked)', 'Extreme color discrimination', 'May cause overload in bright environments'],
        code: 'OPN1MW duplication + OPN1MW2(spectral shift) | X-linked tetrachromacy',
        frequency: '~12% of women carry the genetic variant; fewer than 1% have functional tetrachromacy',
        heritage: 'X-linked; daughters of colorblind fathers are carriers',
        source: 'Jordan & Mollon (1993); Jameson et al. (2001), J Opt Soc Am',
        badges: ['advantage', 'rare'],
      },
      {
        id: 'scn9a_null',
        name: 'SCN9A Null Mutation (CIP)',
        icon: '⚡',
        gene: 'SCN9A',
        snp: 'Various LOF variants (c.2488C>T, c.3482-1G>T, etc.)',
        chr: '2q24.3',
        allele: 'Homozygous LOF',
        mechanism: 'SCN9A encodes Nav1.7 sodium channel required for nociceptive signal transmission. Homozygous null mutations eliminate pain signaling completely. Unlike FAAH-OUT, patients cannot feel any pain or itch but have normal intelligence and motor function.',
        effects: ['Complete congenital insensitivity to pain', 'No itch sensation', 'Normal touch, temperature (partially)', 'Normal cognitive function', 'Risk of unnoticed injuries'],
        code: 'SCN9A LOF (c.2488C>T; p.Arg830Ter) homozygous | CIP OMIM #243000',
        frequency: 'Extremely rare; ~30 families documented worldwide',
        heritage: 'Autosomal recessive; described in Pakistani consanguineous families',
        source: 'Cox et al. (2006), Nature 444:894–898',
        badges: ['rare', 'disorder'],
      },
      {
        id: 'synesthesia_tetartanopia',
        name: 'Grapheme-Color Synesthesia',
        icon: '🎨',
        gene: 'CDC42BPA / ITGA2B (candidate loci)',
        snp: 'rs7632947, rs9883668 (linkage, 2q24)',
        chr: '2q24',
        allele: 'Various — polygenic',
        mechanism: 'Cross-activation between grapheme-processing and color-processing cortical areas. Strongly familial but not Mendelian. Numbers/letters automatically trigger consistent color percepts. Affects ~4% of population.',
        effects: ['Letters/numbers perceived with colors', 'Consistent across lifetime', 'Often aids memory', 'Strong familial pattern'],
        code: 'Polygenic; candidate: 2q24 linkage | rs7632947; CDC42BPA region',
        frequency: '~4% general population; 1:25',
        heritage: 'All populations; slight female bias',
        source: 'Asher et al. (2009), Am J Hum Genet 84(2):279–85',
        badges: ['common', 'advantage'],
      },
      {
        id: 'perfect_pitch',
        name: 'Absolute Pitch (Perfect Pitch)',
        icon: '🎵',
        gene: 'ASAP1 / EPHA5',
        snp: 'rs3057, chr8q22 (ASAP1); chr4q13 linkage',
        chr: '8q22 / 4q13',
        allele: 'ASAP1 rs3057 risk allele; polygenic',
        mechanism: 'Ability to identify/produce any musical note without reference. Requires genetic predisposition + early musical training (critical period <6 yrs). ASAP1 region on chr8 shows strongest GWAS signal. Strong East Asian prevalence may relate to tonal language early exposure.',
        effects: ['Identify any note without reference', 'Perfect musical memory', 'Can be dissonant in bad tuning', 'More common in East Asia'],
        code: 'ASAP1(rs3057) + chr4q13 locus | Polygenic; critical period dependent',
        frequency: '1:10,000 in West; up to 1:1,500 in East Asia (tonal language effect)',
        heritage: 'East Asian, musicians with early training',
        source: 'Athos et al. (2007), PNAS; Theusch & Bhatt (2010)',
        badges: ['rare', 'advantage'],
      },
      {
        id: 'hcrt_narcolepsy',
        name: 'Narcolepsy with Cataplexy',
        icon: '😴',
        gene: 'HLA-DQB1*06:02 + HCRT (orexin)',
        snp: 'HLA-DQB1*0602; HCRT(rs5204)',
        chr: '6p21.32 (HLA); 17q21.2',
        allele: 'HLA-DQB1*0602 + HCRT LOF',
        mechanism: 'Autoimmune destruction of orexin/hypocretin neurons in lateral hypothalamus. HLA-DQB1*0602 allele is present in 95% of narcolepsy-cataplexy patients. Loss of orexin disrupts sleep-wake cycle, triggering sudden muscle weakness (cataplexy) during emotion.',
        effects: ['Excessive daytime sleepiness', 'Cataplexy triggered by emotion', 'Sleep paralysis', 'Hypnagogic hallucinations', 'REM sleep disruption'],
        code: 'HLA-DQB1*0602(+) | HCRT peptide absent | Narcolepsy type 1 OMIM #161400',
        frequency: '1:2,000 globally',
        heritage: 'Universal; Japan highest prevalence (1:600)',
        source: 'Mignot et al. (1997), Cell 98:365–76',
        badges: ['disorder'],
      },
    ]
  },

  metabolic: {
    label: 'Metabolic & Physiological',
    icon: '⚗',
    traits: [
      {
        id: 'epo_mutation',
        name: 'Natural EPO Advantage (EPOR gain-of-function)',
        icon: '🚴',
        gene: 'EPOR',
        snp: 'EPOR(c.5986C>T) gain-of-function; chr19p13.2',
        chr: '19p13.2',
        allele: 'Heterozygous GOF',
        mechanism: 'Gain-of-function mutation in erythropoietin receptor causes elevated RBC production without exogenous EPO. Hematocrit naturally 50–60%. Eero Mäntyranta (Finnish skier) famously carried this variant — won 7 Olympic medals with naturally elevated oxygen transport.',
        effects: ['Hematocrit 50–60% (vs 40–46% normal)', 'VO₂max enhancement', 'Olympic-level endurance advantage', 'Equivalent to blood doping naturally'],
        code: 'EPOR(c.5986C>T; GOF) | Familial erythrocytosis type 1 OMIM #133100',
        frequency: 'Extremely rare; single Finnish family (Mäntyranta) best documented',
        heritage: 'Finnish Sámi ancestry (Mäntyranta family)',
        source: 'de la Chapelle et al. (1993), PNAS 90(10):4495–9',
        badges: ['advantage', 'rare'],
      },
      {
        id: 'mstn_null',
        name: 'Myostatin Deficiency (MSTN)',
        icon: '💪',
        gene: 'MSTN (GDF-8)',
        snp: 'MSTN LOF variants (splice, nonsense)',
        chr: '2q32.2',
        allele: 'Homozygous or heterozygous LOF',
        mechanism: 'Myostatin inhibits muscle growth. LOF mutations cause extraordinary muscle hypertrophy without training. Cases documented in children with 2–4x normal muscle mass. Heterozygous carriers show enhanced athletic performance.',
        effects: ['Extreme muscle mass without exercise', 'Reduced body fat', 'Enhanced athletic performance', 'Normal intelligence', 'Tendon stress risk at extreme'],
        code: 'MSTN LOF (splice site or nonsense) | OMIM #614408',
        frequency: 'Homozygous: extremely rare (<10 documented); Heterozygous: may be 1:1000+',
        heritage: 'Universal; documented in German, American, Finnish cases',
        source: 'Schuelke et al. (2004), NEJM 350:2682–8',
        badges: ['advantage', 'rare'],
      },
      {
        id: 'pcsk9_lof',
        name: 'PCSK9 Loss-of-Function (LDL Protection)',
        icon: '❤',
        gene: 'PCSK9',
        snp: 'rs28362263 (Y142X), rs67608943 (C679X)',
        chr: '1p32.3',
        allele: 'Heterozygous LOF',
        mechanism: 'PCSK9 normally degrades LDL receptors. LOF variants keep LDL receptors active, dramatically lowering LDL cholesterol. Heterozygotes have ~40% lower LDL and 88% lower risk of coronary heart disease. African Americans have 2–3× higher carrier frequency.',
        effects: ['LDL cholesterol ~40–50% lower', '88% lower coronary heart disease risk', 'No known adverse effects', 'Extended healthy lifespan'],
        code: 'PCSK9(Y142X; rs28362263) | OMIM #607786 | Familial hypobetalipoproteinemia type 2',
        frequency: '2.6% African Americans; 0.3% European Americans',
        heritage: 'Enriched in African Americans; East African origin',
        source: 'Cohen et al. (2006), NEJM 354:1264–72',
        badges: ['advantage', 'common'],
      },
      {
        id: 'ldlr_fh',
        name: 'Familial Hypercholesterolemia (FH)',
        icon: '🫀',
        gene: 'LDLR / APOB / PCSK9',
        snp: 'LDLR >3000 variants; APOB(rs5742904); PCSK9(D374Y)',
        chr: '19p13.2 (LDLR); 2p24.1 (APOB)',
        allele: 'Heterozygous (HeFH) or Homozygous (HoFH)',
        mechanism: 'LDL receptor dysfunction → LDL accumulates in blood. HeFH (1:200–300): LDL 4–8 mmol/L; HoFH (1:300,000): LDL >13 mmol/L, heart attacks before 20 without treatment.',
        effects: ['Severely elevated LDL cholesterol', 'Premature cardiovascular disease', 'Xanthomas (cholesterol deposits)', 'Corneal arcus', 'Aortic stenosis (HoFH)'],
        code: 'LDLR LOF variants (>3000 known) | APOB(rs5742904) | FH OMIM #143890',
        frequency: 'HeFH: 1:200–300; most common autosomal dominant disorder worldwide',
        heritage: 'Universal; founder effects in Lebanese, Finnish, Afrikaner',
        source: 'Nordestgaard et al. (2013), Eur Heart J 34:3478–90',
        badges: ['disorder', 'common'],
      },
      {
        id: 'amt_caffeine',
        name: 'Caffeine Metabolism (Fast/Slow)',
        icon: '☕',
        gene: 'CYP1A2',
        snp: 'rs762551 (A/C)',
        chr: '15q24.1',
        allele: 'A/A (fast) vs C allele (slow)',
        mechanism: 'CYP1A2 enzyme metabolizes caffeine. A/A homozygotes metabolize caffeine 4× faster — lower heart disease risk from coffee. C-allele carriers accumulate caffeine → increased MI risk with >2 cups/day.',
        effects: ['A/A: fast metabolism, coffee protective', 'C-allele: slow metabolism, coffee risky', 'Affects anxiety from caffeine', 'Affects sleep disruption from coffee'],
        code: 'CYP1A2(rs762551 A/A) = fast | (A/C or C/C) = slow | chr15q24.1',
        frequency: 'A/A: ~45% population; C-allele carriers: ~55%',
        heritage: 'Universal',
        source: 'Cornelis et al. (2006), JAMA 295(10):1135–41',
        badges: ['common'],
      },
      {
        id: 'amt2',
        name: 'Alcohol Metabolism (ALDH2)',
        icon: '🍺',
        gene: 'ALDH2',
        snp: 'rs671 (ALDH2*2)',
        chr: '12q24.12',
        allele: 'A allele (ALDH2*2)',
        mechanism: 'ALDH2*2 variant enzyme has 6% of normal aldehyde dehydrogenase activity. Acetaldehyde accumulates → Asian flush, nausea, tachycardia. Also protective against alcoholism but dramatically increases esophageal cancer risk in heavy drinkers.',
        effects: ['Asian flush syndrome', 'Acetaldehyde accumulation', 'Protective vs alcoholism', 'Increased esophageal cancer risk with drinking', 'Nausea and headaches from alcohol'],
        code: 'ALDH2(rs671 A/A or G/A) | ALDH2*2 variant | chr12q24.12',
        frequency: '36% East Asians; rare in Europeans/Africans',
        heritage: 'East Asian: Japanese, Korean, Chinese',
        source: 'Chen et al. (1999), Cancer Epidemiol Biomarkers Prev',
        badges: ['common'],
      },
    ]
  },

  skeletal: {
    label: 'Skeletal & Connective Tissue',
    icon: '🦴',
    traits: [
      {
        id: 'marfan',
        name: 'Marfan Syndrome',
        icon: '⬆',
        gene: 'FBN1 (Fibrillin-1)',
        snp: '>3000 pathogenic variants in FBN1; common: c.1A>G, c.7456C>T',
        chr: '15q21.1',
        allele: 'Heterozygous LOF/dominant negative',
        mechanism: 'Fibrillin-1 mutation disrupts extracellular matrix microfibrils → weakened connective tissue. Affects: cardiovascular (aortic root dilation/dissection), skeletal (tall, long limbs, arachnodactyly, scoliosis), ocular (ectopia lentis), pulmonary (spontaneous pneumothorax). Abraham Lincoln likely had Marfan syndrome.',
        effects: ['Tall stature with disproportionately long limbs', 'Arachnodactyly (spider fingers)', 'Aortic root dilation (life-threatening)', 'Ectopia lentis (lens dislocation)', 'Scoliosis', 'Pectus excavatum', 'Myopia', 'Spontaneous pneumothorax'],
        code: 'FBN1 pathogenic variant (heterozygous) | Marfan syndrome OMIM #154700 | Ghent criteria',
        frequency: '1:5,000 globally',
        heritage: 'Universal; autosomal dominant; 25% de novo',
        source: 'Loeys et al. (2010), J Med Genet 47:476–85 (Ghent II criteria)',
        badges: ['disorder', 'rare'],
      },
      {
        id: 'eds',
        name: 'Ehlers-Danlos Syndrome (hEDS)',
        icon: '🤸',
        gene: 'COL5A1 / COL5A2 / TNXB (classical); unknown (hEDS)',
        snp: 'COL5A1 LOF variants; TNXB deletions; hEDS: no single gene',
        chr: '9q34.3 (COL5A1); 6p21.3 (TNXB)',
        allele: 'Heterozygous (classical); polygenic (hEDS)',
        mechanism: 'Collagen synthesis/processing defects → skin hyperextensibility, joint hypermobility, poor wound healing. Classical EDS: COL5A1/COL5A2 mutations. hEDS: most common type but no confirmed gene; likely polygenic. Associated with dysautonomia (POTS), chronic pain.',
        effects: ['Joint hypermobility (beyond normal range)', 'Skin hyperextensibility', 'Atrophic scarring', 'Chronic musculoskeletal pain', 'Dysautonomia/POTS', 'Easy bruising', 'Recurrent joint dislocations'],
        code: 'COL5A1/COL5A2 LOF (classical EDS) | hEDS: no single locus | OMIM #130000',
        frequency: '1:5,000 (all types); hEDS may be 1:500',
        heritage: 'Universal; hEDS female predominant',
        source: 'Malfait et al. (2017), Am J Med Genet Part C 175:8–26',
        badges: ['disorder'],
      },
      {
        id: 'ach',
        name: 'Achondroplasia (Dwarfism)',
        icon: '📐',
        gene: 'FGFR3',
        snp: 'rs28931614 (G1138A; p.Gly380Arg) — accounts for >97% of cases',
        chr: '4p16.3',
        allele: 'Heterozygous GOF (Gly380Arg)',
        mechanism: 'FGFR3 gain-of-function constitutively activates the receptor, suppressing bone elongation in growth plates. Causes rhizomelic short-limb dwarfism (short arms/legs, normal trunk, macrocephaly). 80% are de novo mutations; parents >35 have higher risk.',
        effects: ['Short stature (adult avg 131 cm men, 124 cm women)', 'Rhizomelic short limbs', 'Macrocephaly', 'Midface hypoplasia', 'Normal intelligence', 'Lumbar lordosis', 'Sleep apnea risk'],
        code: 'FGFR3(rs28931614 G1138A; p.Gly380Arg) heterozygous | Achondroplasia OMIM #100800',
        frequency: '1:15,000–40,000 live births; 80% de novo',
        heritage: 'Universal; de novo rate increases with paternal age',
        source: 'Shiang et al. (1994), Cell 78(2):335–42',
        badges: ['disorder'],
      },
    ]
  },

  psychiatric: {
    label: 'Psychiatric & Behavioral',
    icon: '💭',
    traits: [
      {
        id: 'bdnf_val66met',
        name: 'BDNF Val66Met (Memory & Anxiety)',
        icon: '🧩',
        gene: 'BDNF',
        snp: 'rs6265 (Val66Met)',
        chr: '11p14.1',
        allele: 'Met/Met or Val/Met',
        mechanism: 'Met allele impairs activity-dependent BDNF secretion → reduced hippocampal plasticity. Met carriers have smaller hippocampus, worse episodic memory, elevated anxiety, greater depression risk, but also reduced pain sensitivity.',
        effects: ['Reduced episodic memory', 'Smaller hippocampal volume', 'Higher anxiety', 'Greater depression risk', 'Reduced pain sensitivity', 'Reduced response to antidepressants'],
        code: 'BDNF(rs6265 Val66Met) | Met/Met or Val/Met | chr11p14.1',
        frequency: 'Met allele: ~30% European; ~50% East Asian',
        heritage: 'Universal; Met enriched in East Asian populations',
        source: 'Egan et al. (2003), Cell 112(2):257–69',
        badges: ['common'],
      },
      {
        id: 'maoa_warrior',
        name: 'MAOA Low-Activity ("Warrior Gene")',
        icon: '⚔',
        gene: 'MAOA',
        snp: 'MAOA-uVNTR 2R/3R (low activity) vs 4R (high activity)',
        chr: 'Xp11.3',
        allele: '2R or 3R repeat (hemizygous males; homozygous females)',
        mechanism: 'Low-activity MAOA variants produce less monoamine oxidase A → higher serotonin/dopamine/norepinephrine. Associated with elevated impulsivity and aggression risk, especially when combined with adverse childhood experiences. Effect is complex and context-dependent.',
        effects: ['Higher impulsivity tendency (context-dependent)', 'Elevated monoamine levels', 'Greater sensitivity to provocations', 'Modified by childhood environment', 'Possible resilience in some contexts'],
        code: 'MAOA-uVNTR 2R or 3R (low-activity) | Xp11.3 | X-linked',
        frequency: '30–35% of males carry low-activity allele',
        heritage: 'Universal; slightly enriched in populations with specific historical pressures',
        source: 'Caspi et al. (2002), Science 297:851–4; Fergusson et al. (2011)',
        badges: ['common'],
      },
      {
        id: 'drd4_7r',
        name: 'DRD4-7R (Novelty Seeking / ADHD)',
        icon: '🔍',
        gene: 'DRD4',
        snp: 'DRD4 exon III 7-repeat VNTR',
        chr: '11p15.5',
        allele: '7-repeat allele (7R)',
        mechanism: 'DRD4-7R produces a less efficient dopamine receptor → more stimulation required. Associated with novelty seeking, risk-taking, attention deficit, greater food/drug reward seeking. The 7R allele expanded in human populations, suggesting historical advantage for explorers/migrants.',
        effects: ['Novelty and sensation seeking', 'Higher ADHD risk', 'Greater food reward sensitivity', 'Risk-taking behavior', 'Increased responsiveness to stimulants'],
        code: 'DRD4(VNTR exon III 7-repeat) | 11p15.5 | Dopamine receptor D4',
        frequency: '~20% global; ~48% in some nomadic populations (Ariaal)',
        heritage: 'Universal; enriched in populations descended from migratory ancestors',
        source: 'Ding et al. (2002), Hum Mol Genet; Chang et al. (1996), Am J Hum Genet',
        badges: ['common'],
      },
    ]
  },

  immune: {
    label: 'Immune & Infectious Disease',
    icon: '🦠',
    traits: [
      {
        id: 'ccr5_delta32',
        name: 'CCR5-Δ32 (HIV Resistance)',
        icon: '🛡',
        gene: 'CCR5',
        snp: 'rs333 (32bp deletion)',
        chr: '3p21.31',
        allele: 'Homozygous del/del (complete) or del/wt (partial)',
        mechanism: '32bp deletion disrupts CCR5 co-receptor used by HIV-1 to enter cells. Homozygotes are effectively immune to HIV-1 R5-tropic strains. Heterozygotes have delayed AIDS progression. The Berlin Patient and London Patient HIV cures used CCR5-Δ32 donor stem cells.',
        effects: ['Homozygous: near-complete HIV-1 resistance', 'Heterozygous: delayed AIDS progression', 'Slightly increased West Nile virus risk', 'Also reduces some inflammatory conditions'],
        code: 'CCR5(rs333; Δ32bp deletion) del/del | chr3p21.31 | HIV resistance OMIM #601373',
        frequency: '~1% homozygous, ~10–15% heterozygous in Europeans; rare in Africans/Asians',
        heritage: 'Northern European; possibly selected by plague (Y. pestis) 700 years ago',
        source: 'Liu et al. (1996), Cell 86:367–77; Samson et al. (1996), Nature 382:722–5',
        badges: ['advantage', 'rare'],
      },
      {
        id: 'hla_a',
        name: 'HLA-A*11:01 (Superresponder)',
        icon: '💉',
        gene: 'HLA-A',
        snp: 'HLA-A*11:01 allele',
        chr: '6p21.32',
        allele: 'HLA-A*11:01',
        mechanism: 'Certain HLA alleles present peptides to T-cells more broadly. HLA-A*11:01 carriers mount robust immune responses to EBV, CMV, and many cancers. Also associated with carbamazepine hypersensitivity (Stevens-Johnson syndrome) in East Asians.',
        effects: ['Strong antiviral immunity (EBV, CMV)', 'Better tumor surveillance', 'Risk: carbamazepine-induced SJS in East Asians', 'Important for organ transplant matching'],
        code: 'HLA-A*11:01 | 6p21.32 MHC region | Major histocompatibility complex class I',
        frequency: '~25% East Asians; ~5% Europeans',
        heritage: 'Enriched in East Asian and South Asian populations',
        source: 'Chung et al. (2004), Nature 428:486',
        badges: ['common'],
      },
      {
        id: 'sickle_cell_trait',
        name: 'Sickle Cell Trait (Malaria Protection)',
        icon: '🦟',
        gene: 'HBB',
        snp: 'rs334 (Glu6Val; HbS allele)',
        chr: '11p15.4',
        allele: 'Heterozygous HbA/HbS (trait) | Homozygous HbS/HbS (disease)',
        mechanism: 'HBB Glu6Val creates abnormal hemoglobin that polymerizes under low oxygen. Heterozygotes (trait): red cells infected by P. falciparum sickle and are cleared, providing ~90% malaria protection. Homozygotes: sickle cell disease. Classic balanced polymorphism.',
        effects: ['Trait: ~90% protection against severe falciparum malaria', 'Trait: mild sickling risk under extreme conditions (high altitude, surgery)', 'Disease: hemolytic anemia, vaso-occlusive crises, organ damage'],
        code: 'HBB(rs334; Glu6Val) HbA/HbS heterozygous (trait) | Sickle cell trait | OMIM #603903',
        frequency: 'Trait: 8% African Americans; 25–30% in malaria-endemic Africa',
        heritage: 'Sub-Saharan Africa, Middle East, India — malaria-endemic regions',
        source: 'Allison (1954), Br Med J 1:290–4',
        badges: ['advantage', 'disorder', 'common'],
      },
      {
        id: 'duffy_null',
        name: 'Duffy-Null Antigen (Vivax Malaria Resistance)',
        icon: '🛡',
        gene: 'ACKR1 (DARC/Duffy)',
        snp: 'rs2814778 (promoter -46T>C)',
        chr: '1q23.2',
        allele: 'Homozygous C/C (null)',
        mechanism: 'Duffy antigen is receptor for P. vivax malaria. Promoter mutation eliminates DARC expression on red blood cells. P. vivax cannot invade cells without Duffy antigen → complete vivax malaria resistance. Present in >99% of West African populations.',
        effects: ['Complete P. vivax malaria resistance', 'Reduced chemokine-mediated inflammation', 'Lower neutrophil count (not clinically significant)', 'No HIV modifying effect (unlike CCR5)'],
        code: 'ACKR1(rs2814778 -46T>C) C/C homozygous | Duffy-null | chr1q23.2',
        frequency: '>95% West Africans; rare outside Africa',
        heritage: 'West and Central African populations (near-fixation)',
        source: 'Tournamille et al. (1995), Nat Genet 10:224–8',
        badges: ['advantage', 'common'],
      },
    ]
  },

  lifespan: {
    label: 'Lifespan & Aging',
    icon: '⌛',
    traits: [
      {
        id: 'apoe4',
        name: 'APOE ε4 (Alzheimer Risk)',
        icon: '🔬',
        gene: 'APOE',
        snp: 'rs429358 + rs7412 (ε4 haplotype)',
        chr: '19q13.32',
        allele: 'ε4/ε3 (3–4× risk) | ε4/ε4 (8–15× risk)',
        mechanism: 'APOE ε4 isoform binds lipids and clears amyloid-β less efficiently. ε4 carriers accumulate amyloid plaques earlier. Most significant common genetic risk factor for late-onset Alzheimer. Also affects cardiovascular risk and recovery from brain injury.',
        effects: ['3–15× increased Alzheimer risk (dose-dependent)', 'Earlier age of AD onset (~5–10 yrs earlier per allele)', 'Increased LDL cholesterol', 'Worse outcomes after traumatic brain injury', 'Also protective against some parasites'],
        code: 'APOE(rs429358 C + rs7412 C) = ε4 allele | chr19q13.32 | LOAD OMIM #104310',
        frequency: 'ε4 allele: ~14% global; ε4/ε4: ~2% population; 15% Alzheimer patients are ε4/ε4',
        heritage: 'Universal; higher in African ancestry',
        source: 'Corder et al. (1993), Science 261:921–3',
        badges: ['disorder', 'common'],
      },
      {
        id: 'forkhead',
        name: 'FOXO3 Longevity Variant',
        icon: '🌿',
        gene: 'FOXO3',
        snp: 'rs2802292 (G allele)',
        chr: '6q21',
        allele: 'G/G (strongest) or G/T',
        mechanism: 'FOXO3 G allele in intronic region enhances FOXO3 transcription factor activity → better stress resistance, DNA repair, apoptosis regulation, insulin signaling inhibition. Consistently associated with longevity across multiple centenarian cohorts (German, Italian, American, Japanese).',
        effects: ['Increased probability of living to 90+', 'Better cellular stress response', 'Reduced cancer risk (some studies)', 'Improved insulin sensitivity', 'Associated with healthy aging phenotypes'],
        code: 'FOXO3(rs2802292 G/G) | chr6q21 | Longevity association; replicated across 9+ cohorts',
        frequency: 'G allele: ~30–35% European; enriched in centenarians',
        heritage: 'Universal; studied in Ashkenazi Jewish, Japanese, German, Italian centenarians',
        source: 'Willcox et al. (2008), PNAS 105(37):13987–92',
        badges: ['advantage', 'common'],
      },
      {
        id: 'tert_snp',
        name: 'Telomere Length Variants (TERT/TERC)',
        icon: '🔬',
        gene: 'TERT / TERC / RTEL1',
        snp: 'rs2736100 (TERT); rs10936599 (TERC)',
        chr: '5p15.33 (TERT); 3q26.2 (TERC)',
        allele: 'Various — polygenic',
        mechanism: 'Telomere length is partially heritable (~40–80%). Longer telomeres generally associate with longevity but also elevated cancer risk in some studies (paradox). TERT/TERC variants are the strongest genetic determinants of telomere length.',
        effects: ['Longer telomeres: lower cardiovascular disease risk', 'Longer telomeres: slightly elevated cancer risk (lymphoma, melanoma)', 'Shorter telomeres: accelerated aging phenotypes', 'Affects Hayflick limit of cell divisions'],
        code: 'TERT(rs2736100) + TERC(rs10936599) + RTEL1(rs755017) | Polygenic telomere score',
        frequency: 'Common variants; polygenic architecture',
        heritage: 'Universal',
        source: 'Pooley et al. (2013), Nat Genet 45:422–7',
        badges: ['common'],
      },
    ]
  },

};
